### ISSUE TITLE
テーマ作成

### ISSUE THREAD

**Issue by ecogrammer** [ito-artsfarm/itoartsfarm2016-wp#1]

**Comment by ecogrammer** [comment]
bootstrapベースでざっとレイアウトしてみました

![2016 - http___localhost_8023_](https://cloud.githubusercontent.com/assets/90103/15991445/dc14d24a-30ed-11e6-970e-b8fa25fa66f7.jpg)

**Comment by keitakawamoto** [comment]
itoartsfarm2016-staticのテーマを実装
