### ISSUE TITLE
リスト表示でサムネイルが潰れる

### ISSUE THREAD

**Issue by ecogrammer** [ito-artsfarm/itoartsfarm2016-wp#6]
@keitakawamoto 
# 内容

以下の通り、ブラウザが幅の狭い状態（またはスマホ）で表示すると以下のように潰れてしまいます。

http://www.ito-artsfarm.com/blog/

<img width="491" alt="2016-09-13 0 27 43" src="https://cloud.githubusercontent.com/assets/90103/18441717/f68d36aa-7948-11e6-873a-06aff0a71209.png">

WordPressの標準関数 `the_post_thumbnail('thumbnail-500', array('alt' => $title, 'class' => 'image' ));` でサムネイルを出力しているのですが使えない？んでしょうか。

この時間しかissueかけない..

**Comment by ecogrammer** [comment]
https://github.com/ito-artsfarm/itoartsfarm2016-static/issues/4 この辺と原因は同じ？

**Comment by keitakawamoto** [comment]
@ecogrammer 
chrome,safari,firefoxで見てみましたが、こちらでは再現しません。

...と思ったら https://github.com/ito-artsfarm/itoartsfarm2016-wp/commit/fdaf5ffa05350172179d97afe9e36811b5da197d で対応されてましたね。

> ito-artsfarm/itoartsfarm2016-static#4 この辺と原因は同じ？

こちらは、表示を横幅にフィットさせる、というだけで、縦を指定していなければ自動で縦横の比率は維持されますので `縦幅の設定が含まれていなければ` 今回の件とは関係ないです。

予想ですが、万野さんの暫定対応が入る前、スマホサイズの横幅になるとなんらかの縦幅指定が追加されて、つぶれた状態になったのでしょう。

**Comment by keitakawamoto** [comment]
解決した模様
