### ISSUE TITLE
フォームが整っていない

### ISSUE THREAD

**Issue by keitakawamoto** [ito-artsfarm/itoartsfarm2016-wp#7]
![image](https://cloud.githubusercontent.com/assets/1661325/18457383/5cb3d0f2-7993-11e6-840c-d5516808e32f.png)

これまいけませんね、直しましょう

---

@ecogrammer 

ラベル要素を使えばちゃんとスタイリングされます。
![image](https://cloud.githubusercontent.com/assets/1661325/18457409/8f0208ee-7993-11e6-8edb-d05afc2c793b.png)

現在はラベル要素がありませんのでスタイルが効いていません。
![image](https://cloud.githubusercontent.com/assets/1661325/18457419/a339face-7993-11e6-9485-db44638b7f5e.png)
## 

他にも後ほど書きます、お待ちを

**Comment by keitakawamoto** [comment]
https://github.com/ito-artsfarm/itoartsfarm2016-wp/blob/master/css/style.css#L345 このあたりに `input[type="tel"],` を追加で解決可能。

> ラベル要素を使えばちゃんとスタイリングされます。

これはちょっと相談

**Comment by keitakawamoto** [comment]
![image](https://cloud.githubusercontent.com/assets/1661325/18930645/c83baa44-8603-11e6-8255-6d02cac15474.png)

これは
フォームに見出しを作って、ボタンは行為の名称だけにしたほうがいい
ボタンがタイトルみたいになってしまっている。

## ドミニクチェンのトークセッションに参加しますか？

フォーム
フォーム
フォーム
フォーム

[参加します]

...こんな感じ。

**Comment by ecogrammer** [comment]
@keitakawamoto `input[type="tel"]` 試してみます！

**Comment by keitakawamoto** [comment]
あざます！ @ecogrammer 記事内のフォームって、どうやって生成してます？ https://github.com/ito-artsfarm/itoartsfarm2016-wp/issues/7#issue-176518316 このラベルの件...

**Comment by ecogrammer** [comment]
@keitakawamoto Contact Form7 (プラグイン) が自動生成しています。 `wpc7~` ってclassがあたっているところが生成されている部分ですねー。

![2016-09-29 9 12 57](https://cloud.githubusercontent.com/assets/90103/18936753/0e1b4d14-8625-11e6-85fa-b6fcdd33a1c2.png)

**Comment by keitakawamoto** [comment]
それがわかれば対応可能そうです！

**Comment by keitakawamoto** [comment]
![image](https://cloud.githubusercontent.com/assets/1661325/19115022/57e875c2-8b4b-11e6-8ea7-c9ddba15c52d.png)
くっ...要素がない。自動生成でこれでは、指定が難しい。保留で..
